<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Sandy-PC" name="com.Vtiger.tc.CreatePurchaseOrderWithItemWithoutEnteringListPrice" tests="1" failures="1" timestamp="26 Apr 2021 15:00:15 GMT" time="5.102" errors="0">
  <testcase name="CreatePurchaseOrderWithItemWithoutEnteringListPrice" time="5.102" classname="com.Vtiger.tc.CreatePurchaseOrderWithItemWithoutEnteringListPrice">
    <failure type="java.lang.AssertionError" message="Homepage  pass expected [Homee] but found [Home]">
      <![CDATA[java.lang.AssertionError: Homepage  pass expected [Homee] but found [Home]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at com.Vtiger.tc.CreatePurchaseOrderWithItemWithoutEnteringListPrice.CreatePurchaseOrderWithItemWithoutEnteringListPrice(CreatePurchaseOrderWithItemWithoutEnteringListPrice.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreatePurchaseOrderWithItemWithoutEnteringListPrice -->
</testsuite> <!-- com.Vtiger.tc.CreatePurchaseOrderWithItemWithoutEnteringListPrice -->
